name: Lint Markdown

on: push


jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint Markdown files
        uses: avto-dev/markdown-lint@v1
        with:
          config: '.markdownlint.json'
        continue-on-error: false
